### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by geilige** [geilige/dex2jar#1]
`java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	    at java.lang.String.substring(String.java:1967)
	    at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:169)
	    at org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:130)
	    at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:162)
	    at org.objectweb.asm.commons.RemappingClassAdapter.visitField(RemappingClassAdapter.java:90)
	    at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:272)
	    at com.googlecode.d2j.dex.Dex2Asm.convertField(Dex2Asm.java:531)
	    at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:482)
	    at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:400)
	    at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:503)
	    at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	    at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	    at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	    at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)`

**Comment by ThexXTURBOXx** [comment]
This error has been fixed in my fork: https://github.com/ThexXTURBOXx/dex2jar

Thanks for your work btw, really appreciate it!
